# Generated by Django 5.2.6 on 2025-09-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opponent_logo',
            field=models.ImageField(default='./media/team_logos/nfl.png', upload_to='./media/team_logos/'),
        ),
    ]
