# Generated by Django 5.2.6 on 2025-09-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_game_opponent_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='opponent_logo',
            field=models.ImageField(default='team_logos/nfl.png', upload_to='team_logos/'),
        ),
    ]
